### ISSUE TITLE
Bumping OTel Agent to 1.13.0 causes startup warning messages `MetricStorageRegistry - Found duplicate metric definition...`

### ISSUE THREAD

**Issue by cyrille-leclerc** [cyrille-leclerc/my-shopping-cart#21]
Bumping OTel Agent to 1.13.0 causes startup warning messages `MetricStorageRegistry - Found duplicate metric definition...`

```
2022-04-21 15:06:10.443  INFO 7635 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1947 ms
[otel.javaagent 2022-04-21 15:06:10:644 +0200] [main] WARN io.opentelemetry.sdk.metrics.internal.state.MetricStorageRegistry - Found duplicate metric definition: jvm.threads.states
    at io.opentelemetry.micrometer1shim.OpenTelemetryGauge.<init>(OpenTelemetryGauge.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newGauge(OpenTelemetryMeterRegistry.java:71)
    at io.micrometer.core.instrument.MeterRegistry.lambda$gauge$1(MeterRegistry.java:298)
    ...
Causes
- Description [The current number of threads having RUNNABLE state] does not match [The current number of threads having NEW state]
- InstrumentDescription [The current number of threads having RUNNABLE state] does not match [The current number of threads having NEW state]
Original instrument registered with same name but is incompatible.
    at io.opentelemetry.micrometer1shim.OpenTelemetryGauge.<init>(OpenTelemetryGauge.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newGauge(OpenTelemetryMeterRegistry.java:71)
    at io.micrometer.core.instrument.MeterRegistry.lambda$gauge$1(MeterRegistry.java:298)
    ...
[otel.javaagent 2022-04-21 15:06:10:645 +0200] [main] WARN io.opentelemetry.sdk.metrics.internal.state.MetricStorageRegistry - Found duplicate metric definition: jvm.threads.states
    at io.opentelemetry.micrometer1shim.OpenTelemetryGauge.<init>(OpenTelemetryGauge.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newGauge(OpenTelemetryMeterRegistry.java:71)
    ...
Causes
- Description [The current number of threads having BLOCKED state] does not match [The current number of threads having NEW state]
- InstrumentDescription [The current number of threads having BLOCKED state] does not match [The current number of threads having NEW state]
Original instrument registered with same name but is incompatible.
    at io.opentelemetry.micrometer1shim.OpenTelemetryGauge.<init>(OpenTelemetryGauge.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newGauge(OpenTelemetryMeterRegistry.java:71)
    ...
[otel.javaagent 2022-04-21 15:06:10:646 +0200] [main] WARN io.opentelemetry.sdk.metrics.internal.state.MetricStorageRegistry - Found duplicate metric definition: jvm.threads.states
    at io.opentelemetry.micrometer1shim.OpenTelemetryGauge.<init>(OpenTelemetryGauge.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newGauge(OpenTelemetryMeterRegistry.java:71)
    at io.micrometer.core.instrument.MeterRegistry.lambda$gauge$1(MeterRegistry.java:298)
    ...
Causes
- Description [The current number of threads having WAITING state] does not match [The current number of threads having BLOCKED state]
- InstrumentDescription [The current number of threads having WAITING state] does not match [The current number of threads having BLOCKED state]
Original instrument registered with same name but is incompatible.
    at io.opentelemetry.micrometer1shim.OpenTelemetryGauge.<init>(OpenTelemetryGauge.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newGauge(OpenTelemetryMeterRegistry.java:71)
    ...
[otel.javaagent 2022-04-21 15:06:10:646 +0200] [main] WARN io.opentelemetry.sdk.metrics.internal.state.MetricStorageRegistry - Found duplicate metric definition: jvm.threads.states
    at io.opentelemetry.micrometer1shim.OpenTelemetryGauge.<init>(OpenTelemetryGauge.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newGauge(OpenTelemetryMeterRegistry.java:71)
    at io.micrometer.core.instrument.MeterRegistry.lambda$gauge$1(MeterRegistry.java:298)
    ...
Causes
- Description [The current number of threads having TIMED_WAITING state] does not match [The current number of threads having BLOCKED state]
- InstrumentDescription [The current number of threads having TIMED_WAITING state] does not match [The current number of threads having BLOCKED state]
Original instrument registered with same name but is incompatible.
    at io.opentelemetry.micrometer1shim.OpenTelemetryGauge.<init>(OpenTelemetryGauge.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newGauge(OpenTelemetryMeterRegistry.java:71)
    at io.micrometer.core.instrument.MeterRegistry.lambda$gauge$1(MeterRegistry.java:298)
    ...
[otel.javaagent 2022-04-21 15:06:10:647 +0200] [main] WARN io.opentelemetry.sdk.metrics.internal.state.MetricStorageRegistry - Found duplicate metric definition: jvm.threads.states
    at io.opentelemetry.micrometer1shim.OpenTelemetryGauge.<init>(OpenTelemetryGauge.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newGauge(OpenTelemetryMeterRegistry.java:71)
    at io.micrometer.core.instrument.MeterRegistry.lambda$gauge$1(MeterRegistry.java:298)
    ...

Causes
- Description [The current number of threads having TERMINATED state] does not match [The current number of threads having TIMED_WAITING state]
- InstrumentDescription [The current number of threads having TERMINATED state] does not match [The current number of threads having TIMED_WAITING state]
Original instrument registered with same name but is incompatible.
    at io.opentelemetry.micrometer1shim.OpenTelemetryGauge.<init>(OpenTelemetryGauge.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newGauge(OpenTelemetryMeterRegistry.java:71)
    at io.micrometer.core.instrument.MeterRegistry.lambda$gauge$1(MeterRegistry.java:298)
    ...
[otel.javaagent 2022-04-21 15:06:10:652 +0200] [main] WARN io.opentelemetry.sdk.metrics.internal.state.MetricStorageRegistry - Found duplicate metric definition: logback.events
    at io.opentelemetry.micrometer1shim.OpenTelemetryCounter.<init>(OpenTelemetryCounter.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newCounter(OpenTelemetryMeterRegistry.java:76)
    at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:562)
    ...
Causes
- Description [Number of warn level events that made it to the logs] does not match [Number of error level events that made it to the logs]
- InstrumentDescription [Number of warn level events that made it to the logs] does not match [Number of error level events that made it to the logs]
Original instrument registered with same name but is incompatible.
    at io.opentelemetry.micrometer1shim.OpenTelemetryCounter.<init>(OpenTelemetryCounter.java:43)
    at io.opentelemetry.micrometer1shim.OpenTelemetryMeterRegistry.newCounter(OpenTelemetryMeterRegistry.java:76)
    at io.micrometer.core.instrument.MeterRegistry.lambda$registerMeterIfNecessary$5(MeterRegistry.java:562)
    at io.micrometer.core.instrument.MeterRegistry.getOrCreateMeter(MeterRegistry.java:620)
    ...
```

**Detailed startup logs**

https://gist.github.com/cyrille-leclerc/40e94da3b81083fa8b1b6b441d8d8639

**Comment by cyrille-leclerc** [comment]
Duplicate of 
* https://github.com/open-telemetry/opentelemetry-java/issues/4381
